### ISSUE TITLE
field_name.context = self.context AttributeError: can't set attribute

### ISSUE THREAD

**Issue by Xepe** [Nepherhotep/django-rest-framework-dyn-serializer#6]
Hello, 

I am using Django rest framework 3.6.4 and I am getting the following error: 

> File "/home/vagrant/.virtualenvs/api/lib/python3.6/site-packages/rest_framework_dyn_serializer.py", line 44, in __init__
> field_name.context = self.context
> AttributeError: can't set attribute

I think that the error is related to the following change in the version 3.6.4:

https://github.com/encode/django-rest-framework/pull/5313/commits/563020e2c590896bf0763653887ac9a46b5a858c

You can see in the line 599 that @cached_property is not longer used, and it was replaced for @property,  I think that the (for in ) in line https://github.com/Nepherhotep/django-rest-framework-dyn-serializer/blob/master/rest_framework_dyn_serializer.py#L43 is not need anymore, but I am not totally sure. 

Regards.

**Comment by Nepherhotep** [comment]
Hey @Xepe, thanks for noticing the problem. I'll add your running configuration to Travis config and test myself. By the way, what Python version do you use (just in case)?

**Comment by Xepe** [comment]
Hello

Right now I am using Python 3.6.1+, but the issue only happens using Django rest framework 3.6.4

Regards,

**Comment by Nepherhotep** [comment]
@Xepe the issue reproduced, will nail it soon.

**Comment by Nepherhotep** [comment]
Hey, @Xepe the issue solved (please see 1.2.1 version). For now I set **self._context = context** and it's passing all the tests. You can use this version, however, soon I'll investigate if just removing context out from serializer will be a correct solution (doesn't affect your code anyway).
Thanks again for reporting the problem :)
