### ISSUE TITLE
Limit fields during declaration

### ISSUE THREAD

**Issue by radyz** [Nepherhotep/django-rest-framework-dyn-serializer#8]
Is it possible to limit fields when declared so that a model serializer can be re-used, e.g:

```UserModelSerializer(fields=('id', 'first_name', 'last_name',))```

This way I can re-use the UserModelSerializer in other places without exposing additional info such as username, email etc when nesting it.

**Comment by Nepherhotep** [comment]
Hey @radyz, no it doesn't support that - at the moment fields always load from Meta. Maybe in future I update this behavior, however pull requests are welcome :)

**Comment by Nepherhotep** [comment]
@radyz great thanks for contribution!
